### PR TITLE
iOS Fix failing wordpress examples

### PR DESCRIPTION
**Pull request by jmoody**
### Motivation

* Wait for network activity to finish before proceeding
* Don't auto fail on the iOS swipe-to-delete row example
  - Demonstrate how to handle this real-world problem.
* The delete-post UI is different on Android and iOS.
  - Demonstrate how to partition the test suite with @android and @ios tags
* Tapping the post title causes an animation (the Navigation bar animates off),
  so we cannot use clear_text_in. :(
* Speed up iOS testing - use shorter post titles and bodies
* Don't call stop_app in the After hook
  - Skeleton: After hook should not call stop_app by default #211

This is WIP because I need to make a release for the `delete post` to work.

### CODE REVIEW

**Comment by krukow** [comment]
@jmoody what change is needed for delete post to work?

**Comment by jmoody** [comment]
@krukow I need to add some support in `pan` for detecting the gesture on table view cells.

The original Scenario just failed with a message about "Delete not being part of the UI".

I've figured out that `dragInsideWithOptions` only fails on:

* UIScrollView and subclasses of UIScrollView
* On views that are found inside UIScrollView (or subclasses).

Rather than failing automatically when pan is called on an iOS Simulator, I try to detect those two conditions and fail with a better error message.

This is the Scenario:

```
@ios
Scenario: Deleting a post
  Given I have added a post
  When I try to swipe-to-delete that post on a simulator
  Then I expect an error about a broken Apple API
  But I can delete that post on a device
```

**Comment by krukow** [comment]
@jmoody OK - cool.

**Comment by jmoody** [comment]
@krukow  You should see all green on the iOS Wordpress Scenarios.

**Comment by jmoody** [comment]
@krukow Hold that!  I need to make a new pre-release.

**Comment by jmoody** [comment]
@krukow Released!

**Pull request merged**
