### PR TITLE
iOS implement console_attach

### PR DESCRIPTION
**Pull request by jmoody**
### Motivation

I encountered some problems with gestures and in order to debug them, I need `console_attach` in the console.

### Tests

```
$ be rspec spec/integration/ios/console_helpers.rb
```

### CODE REVIEW

**Comment by TobiasRoikjer** [comment]
Can't we just do console_attach by default? That's how I would expect it from the Android side

**Comment by jmoody** [comment]
It is not that simple.  We can't know which strategy to use to attach.

And it takes a long time to attach.  Sometimes you just want to query - attaching is only necessary for gestures and UIAutomation.

**Comment by TobiasRoikjer** [comment]
@jmoody If I tried to perform a gesture before attaching, would the console tell me to run `console_attach` first?

**Comment by jmoody** [comment]
No.  You get an exception:

```
> tap('textField')
Calabash::IOS::RouteError: This device does not have a connection to run-loop.  Call start_app first.
```

This is just one of the many things I have to fix.

**Comment by TobiasRoikjer** [comment]
@jmoody kioi

**Pull request merged**
