### PR TITLE
Remove cucumber dependency

### PR DESCRIPTION
**Pull request by jmoody**
### Motivation

Why do we depend on cucumber? :)

The only tool that needs this is the run-command.  Otherwise it is not necessary.

I realize we are a cucumber tool, but this change might push folks toward using a Gemfile.

At the very least, let's remove the slowhandcuke dependency _unless_ we are going to included it in the skeleton.

### CODE REVIEW

**Comment by jmoody** [comment]
@TobiasRoikjer PR is based on our discussion today.

cc @krukow @jonasmaturana @olefriis 

We are serious.  Should we be including cucumber as a dependency?

The question came up because we are not sure yet what it means to support 1.3.* and 2.*.

**Comment by krukow** [comment]
@jmoody What do you mean by "The question came up because we are not sure yet what it means to support 1.3.* and 2.*."? and what does removing the dependency mean with respect to that?

**Comment by jmoody** [comment]
>> not sure yet what it means to support **[cucumber]** 1.3.* and 2.*."
> what does removing the dependency mean with respect to that?

If it turns out that we need to branch on the cucumber version when generating our skeleton or at runtime, then I would say we should only support cucumber 2.0.  In which case, I would keep the cucumber dependency.

If it turns out there is no difference to Calabash, then I think dropping the dependency is not a bad idea.  This would make Calabash test-runner agnostic (at least locally) - someone could implement an rspec runner for example.

My personal opinion is that we should drop 1.3 support and require cucumber 2.0 by keeping it as gem dependency.  I am, however, open to removing the dependency all together.

**Comment by krukow** [comment]
"My personal opinion is that we should drop 1.3 support and require cucumber 2.0 by keeping it as gem dependency. I am, however, open to removing the dependency all together."

@jmoody ^ I have the same opinion. I don't see a great benefit of not depending on cucumber and it will require an extra command for most users to install

 (we probably need `'cucumber', '~> 2.0'`)

**Comment by jmoody** [comment]
@TobiasRoikjer Cannot merge this because (the old) calabash-android is depending on cucumber; probably the embed patch?

```
/home/travis/build/calabash/calabash/old/android/ruby-gem/lib/calabash-android/operations.rb:16
```

**Comment by TobiasRoikjer** [comment]
@jmoody Can we just install cucumber on travis for now?

**Comment by TobiasRoikjer** [comment]
@jmoody I have just rebased this
can we merge?

**Pull request merged**
