### PR TITLE
Wordpress: update the gemfile and docs

### PR DESCRIPTION
**Pull request by jmoody**
### Motivation

We need to pin the version to 1.9.9.pre2 (or the most recent release).  Otherwise, we have to mention users must run:

* copy_repos.sh
* change_old_files.sh
* be rake android:build

README.md - There is no need to resign or build the apk; you can just `run`.  Hurray!  +1 @TobiasRoikjer

### CODE REVIEW

**Comment by jmoody** [comment]
@krukow Just want to make sure you saw this change in advance of your presentation.

**Comment by krukow** [comment]
@jmoody not sure what's up. I ran this yesterday...

**Comment by jmoody** [comment]
@krukow Are you not able to run now?

**Comment by krukow** [comment]
@jmoody yes - both before and after

**Comment by jmoody** [comment]
@krukow 

Have you pulled the latest from develop?

Does the Gemfile point to 'calabash', '1.9.9.pre2'?

Try deleting the samples/wordpress/test_servers directory.

@TobiasRoikjer will have to take from there...

**Comment by krukow** [comment]
@jmoody - sorry I meant - everything works as did it work before this pull request :)

**Comment by jmoody** [comment]
@krukow The gist of the change is that you don't have to build or resign on Android.  Just `calabash run path/to/apk`.

**Pull request merged**
